lsi: false
safe: true
source: https://ianmfraser.github.io
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
baseurl: /imf-musicsite